Fix Fastino power cycling issue after flashing
quartiq/kasli-i2c pull request #9
Opened 2021-10-08 11:07 UTC by jmatyas

2021-10-08 11:15 UTC, jordens requested changes
* in #8 you suggest swapping the config and the enable. But now you swap enable and state setting. Why? I'd prefer the former.
* please add a note in the commit that will automatically clos the issue #8 and reference it.

2021-10-08 13:02 UTC, jmatyas commented
* that's one thing I didn't mention in an issue because I discovered it a bit later . Expander's outputs are configured as SS by default so if you write a value to the expander register before its configuration as GPIO, it has no effect. You can experience it just after the power cycle - reading from the GPIO reg gives you 0xD even though you wrote to the reg 0x1.
  * OK

2021-10-08 13:19 UTC, jordens commented
Ack!

2021-10-28 16:04 UTC, jordens approved these changes

2021-10-28 16:04 UTC, merged